# Model arguments
model_name_or_path: unsloth/Qwen3-4B-Base
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Model arguments
load_in_4bit: false
load_in_8bit: false            # Use 16bit training
bnb_4bit_quant_type: nf4
use_peft: true
lora_r: 32                     # NOTE: Alternatively 16 and 64 if underfitting
lora_alpha: 64
lora_dropout: 0.1
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
lora_task_type: "CAUSAL_LM"
# vllm parameters
gpu_memory_utilization: 0.95
enforce_eager: true

# Data training arguments
dataset_name: atomwalk12/linalgzero-grpo
dataset_config: default
eval_dataset_name: atomwalk12/linalgzero
eval_dataset_config: default
dataset_num_proc: 12
dataset_text_field: text
eos_token: <|im_end|>

# GRPO trainer config
bf16: true

## Evaluation parameters
do_eval: true                  # does a final evaluation step at the end of training
eval_on_start: false           # does an evaluation step at the start of training
eval_strategy: 'steps'         # can be "no","epoch","steps"
eval_steps: 50
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
save_total_limit: 5
eval_max_new_tokens: 4096
# NOTE: for early stopping:
#  - early_stopping_patience (3)
#  - early_stopping_threshold (0.01)
#  - callback (early_stopping)

#callbacks:
#  - tool_calling_accuracy
#  - push_to_hub_revision


## Training parameters
# NOTE: adjust batch size, lr
gradient_accumulation_steps: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: atomwalk12/Qwen3-4B-Base-GRPO
hub_strategy: every_save
learning_rate: 2e-5 # Alternatives: 4e-5/3e-5/2e-5 and train for 2 epochs
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_grad_norm: 0.2
max_seq_length: 8192
max_length: 8192
max_steps: -1
num_train_epochs: 1               # NOTE: Alternatively 2 if underfitting
output_dir: results/Qwen3-4B-Base-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
report_to:
- wandb
save_strategy: steps
save_steps: 50
seed: 42
use_liger_kernel: false     # Supported only for Llama, Mistral, Mixtral, and Gemma models
warmup_ratio: 0.03
chat_template_path: linalg_zero/sft/chat_templates/Qwen/Qwen3-4B-Base.jinja
optim: adamw_torch_fused
