# Run config
model_provider: "<placeholder>"
user_model_provider: "<placeholder>"
model: "gpt-4.1"
user_model: "gpt-4o"
num_trials: 1
env: "retail"
agent_strategy: "tool-calling"
temperature: 0.0
task_split: "test"
start_index: 0
end_index: -1
task_ids: None
log_dir: "results"
max_concurrency: 1
seed: 10
shuffle: 0
user_strategy: "llm"
few_shot_displays_path: None
report_to:
- wandb

## art related configs
api_key: None
base_url: None
reward_type: "real"
judge_model: "o3"
max_num_steps: 30
skip_eval: false
add_shadow_trajectory: false
messages_only: false
base_model: "unsloth/Qwen2.5-14B-Instruct"
is_multi_gpu: false
add_no_think: false
plot_tensors: false


# GRPO config
trajectories_per_group: 6
groups_per_step: 10
learning_rate: 1.2e-5
eval_steps: 10
val_set_size: 85
training_dataset_size: 30
num_epochs: 50
train_mode: "sync_rl"
importance_sampling_level: "token"
