# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# LoRA arguments
load_in_4bit: true
bnb_4bit_quant_type: nf4
use_peft: true
lora_r: 16                     # NOTE: Alternatively 32 and 64 if underfitting
lora_alpha: 32
lora_dropout: 0.1
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
lora_task_type: "CAUSAL_LM"

# Data training arguments
dataset_name: atomwalk12/linalgzero-distilled
dataset_config: default
eval_dataset_name: atomwalk12/linalgzero
eval_dataset_config: default
dataset_num_proc: 12
eos_token: <|im_end|>

# SFT trainer config
bf16: true

## Evaluation parameters
do_eval: true                  # does a final evaluation step at the end of training
eval_on_start: true            # does an evaluation step at the start of training
eval_strategy: 'steps'         # can be "no","epoch","steps"
eval_steps: 50                 # run evaluation every N training iterations
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
early_stopping_patience: 3
early_stopping_threshold: 0.01
save_total_limit: 5
eval_max_new_tokens: 2048
callbacks:
  - tool_calling_accuracy
  - early_stopping

## Training parameters
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen3-1.7B-Instruct-SFT
hub_strategy: every_save
learning_rate: 2e-5
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_grad_norm: 0.2
max_length: 32768
max_steps: -1
num_train_epochs: 1               # NOTE: Alternatively 2 if underfitting
output_dir: results/Qwen3-1.7B-Instruct-SFT
overwrite_output_dir: true
per_device_eval_batch_size: 32
per_device_train_batch_size: 8
push_to_hub: true
report_to:
- wandb
save_strategy: steps
save_steps: 50
seed: 42
use_liger_kernel: true
warmup_ratio: 0.03
